-- Schema initial PulseTrack : compte, profil sportif, seances et trace GPS.
-- Les identifiants metier sont des UUID : ils sont generes cote application, ce
-- qui permet a un client mobile hors ligne de creer une seance sans aller-retour.

create table users (
    id            uuid         primary key,
    email         varchar(320) not null,
    password_hash varchar(100) not null,
    created_at    timestamptz  not null
);

-- L'email est normalise en minuscules par le service avant insertion : l'unicite
-- est donc reellement insensible a la casse.
create unique index ux_users_email on users (email);

create table user_profiles (
    id                uuid          primary key,
    user_id           uuid          not null references users (id) on delete cascade,
    display_name      varchar(80)   not null,
    height_cm         integer       not null,
    current_weight_kg double precision not null,
    birth_date        date,
    sex               varchar(20),
    primary_goal      varchar(40)   not null,
    fitness_level     varchar(20)   not null,
    created_at        timestamptz   not null,
    updated_at        timestamptz   not null
);

-- Un seul profil par compte.
create unique index ux_user_profiles_user on user_profiles (user_id);

create table user_profile_preferred_sports (
    user_profile_id uuid        not null references user_profiles (id) on delete cascade,
    sport           varchar(20) not null,
    primary key (user_profile_id, sport)
);

create table workout_sessions (
    id                          uuid             primary key,
    user_id                     uuid             not null references users (id) on delete cascade,
    sport_type                  varchar(20)      not null,
    started_at                  timestamptz      not null,
    ended_at                    timestamptz      not null,
    duration_seconds            bigint           not null,
    moving_duration_seconds     bigint           not null,
    distance_meters             double precision not null,
    -- Nul quand la distance est nulle (seance sans deplacement) : une allure
    -- n'a alors aucun sens, et 0 se lirait comme "infiniment rapide".
    average_pace_seconds_per_km integer,
    average_speed_kmh           double precision not null,
    max_speed_kmh               double precision not null,
    elevation_gain_meters       double precision not null,
    calories_burned             integer          not null,
    perceived_effort            integer,
    feeling                     varchar(20),
    note                        varchar(2000),
    created_at                  timestamptz      not null
);

-- Index de l'ecran historique : les seances d'un utilisateur, les plus recentes
-- d'abord. Couvre aussi les agregats hebdomadaires filtres par periode.
create index ix_workout_sessions_user_started on workout_sessions (user_id, started_at desc);

create table gps_points (
    id                 bigint           generated by default as identity primary key,
    workout_session_id uuid             not null references workout_sessions (id) on delete cascade,
    position           integer          not null,
    latitude           double precision not null,
    longitude          double precision not null,
    altitude           double precision,
    accuracy           double precision,
    speed              double precision,
    recorded_at        timestamptz      not null
);

-- `position` conserve l'ordre du trace : sans lui, rien ne garantit que la base
-- rende les points dans l'ordre de parcours.
create unique index ux_gps_points_session_position on gps_points (workout_session_id, position);
