-- Sequence dediee aux points GPS, pour permettre l'ecriture par lots.
--
-- `generated by default as identity` oblige Hibernate a recuperer la cle apres
-- chaque insertion, ce qui interdit tout regroupement : une trace de 10 800
-- points, soit trois heures de course a un point par seconde, coute alors
-- 10 800 allers-retours — mesure a 12 s en local, et bien davantage sur un
-- serveur modeste. Au-dela du delai d'attente du client mobile, l'utilisateur
-- voit sa seance echouer alors qu'elle est enregistree.
--
-- En tirant les identifiants d'une sequence, Hibernate les connait avant
-- d'ecrire et peut grouper les insertions.
--
-- La colonne n'est pas modifiee : `by default` accepte une valeur fournie
-- explicitement, et l'identite reste disponible pour toute insertion faite
-- hors de l'application. On evite ainsi un `alter column` sur une table qui
-- peut deja contenir des millions de lignes.
do $$
declare
    -- Un intervalle confortable au-dessus des identifiants existants : les deux
    -- generateurs coexistent, ils ne doivent jamais se rejoindre.
    premiere_valeur bigint;
begin
    select coalesce(max(id), 0) + 1000 into premiere_valeur from gps_points;
    execute format(
        -- Le pas de 50 doit rester egal a `allocationSize` cote entite : un
        -- ecart entre les deux produirait des cles en double.
        'create sequence gps_points_seq increment by 50 start with %s',
        premiere_valeur);
end $$;
